#pragma once
//#define TINYOBJLOADER_IMPLEMENTATION
//#include "Dependancies/Tiny-Obj-Loader/tiny_obj_loader.h"
#include <stdio.h>
#include <string>
#include "Shader.h"
#include "Error.h"
#include "Init.h"
#include "Mesh.h"
#include "Camera.h"
#include "Input.h"
#include "SceneTree.h"